# Generated by Django 5.1.1 on 2024-09-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
